knpu_oauth2_client:
    clients:
        discord:
            type: discord
            client_id: '%env(DISCORD_ID)%'
            client_secret: '%env(DISCORD_SECRET)%'
            redirect_route: connect_discord_check
            redirect_params: {}
                
        # twitch:
        #     type: twitch
        #     client_id: '%env(TWITCH_ID)%'
        #     client_secret: '%env(TWITCH_SECRET)%'
        #     redirect_route: connect_twitch_check
        #     redirect_params: {}

        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
